### ISSUE TITLE
Function return

### ISSUE THREAD

**Issue by kseiders** [AmrDeveloper/Turtle#1]
**Describe the bug**
Functions don't properly resume from where called. Causes issues with recursive functions, like fractal trees

**To Reproduce**
Simple fractal tree:
move 375, 500
let colors =[RED, BLUE, GREEN, YELLOW]
let angle =30
rotate 90
fun y(level){
	if(level >0){
		color colors[level %4]
		forward level*10
		rotate 360-angle
		y(level-1)
		rotate 2*angle
		y(level - 1)
		rotate 360-angle
		backward level *10
	}
}
y(10)

**Expected behavior**
Should make a fractal tree, not a simple spiral.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: moto pure
 - OS: Android 10

**Additional context**

**Comment by AmrDeveloper** [comment]
Hello @kseiders,

Thank you for your report, I will test it and fix it in next release

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
The bug is solved now :D, your code will work as expected in Release 1.3.1

Demo

https://user-images.githubusercontent.com/23631699/191572988-934b09a9-7025-4444-94ec-2ed849f67610.mp4
