### ISSUE TITLE
Using Comments ...

### ISSUE THREAD

**Issue by boa2145** [AmrDeveloper/Turtle#2]
Hi, I would like to use comments in my turtle's source code. Is this possible? Regards ... Gregor

**Comment by AmrDeveloper** [comment]
Hi Gregor,

Thanks for creating this issue, i implemented a single line comment support like Python

# comment

I will release it today and you can use it

Thanks
Amr Hesham

**Comment by boa2145** [comment]
Hi Amr, Thanks for your reply and that you implemented a single line comment support with # in Python. Regards ... Gregor

**Comment by boa2145** [comment]
Thank you, Amr Hesham! :)

Amr Hesham ***@***.***> schrieb am Mi., 17. Juli 2024, 20:30:
