### ISSUE TITLE
Using PenDown() and PenUp() ...

### ISSUE THREAD

**Issue by boa2145** [AmrDeveloper/Turtle#3]
Hi Amr, I have a further issue. I think in your turtle-app it is not possible to use the methods PenDown() and PenUp() for the turtle. Is that right? I only noticed the methods Hide() and Show(), but I would like to see the movement of the turtle, if I change the position. Could you, please, implement these two methods for the turtle. It would be nice. Regards ... Gregor

**Comment by AmrDeveloper** [comment]
Hello @boa2145,

Thank you for suggestions, i will implement it in next release soon

Thank you
Amr Hesham

**Comment by boa2145** [comment]
Hello Amr, Thanks for your message. I am going to wait unti you will have implemented the penDown() and penUp() methods. It is fine to use your Android app to program with the turtle. I like turtle programming with Python, Small Basic and Scratch very much. Now I am able to do this with your app, top. Regards ... Gregor

**Comment by AmrDeveloper** [comment]
Happy to know that you loved it, i implemented penUp and penDown now and uploaded it to google play so it will take one or two days and will be live to use and enjoy it :D

Thank you
Amr Hesham
